name: ✨ Enhancement idea
description: General idea for improving the project or requesting new features
labels: ["✨ Enhancement", "👀 Evaluation"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that our enhancement idea form is appropriate for you.
      options:
        - label: My idea doesn't duplicate an existing SteamBadgesDB functionality or an already **[rejected](https://github.com/nolddor/steam-badges-db/issues?q=label%3A"👎+Won't+do")** request.
          required: true
        - label: I believe that my idea falls into this project scope and should be offered as a built-in functionality
          required: true
        - label: My idea doesn't violate the **[Steam Subscriber Agreement](https://store.steampowered.com/subscriber_agreement)**
          required: true
        - label: My idea doesn't violate the **[Steam Online Conduct](https://store.steampowered.com/online_conduct)**
          required: true
  - type: textarea
    id: enhancement-purpose
    attributes:
      label: Enhancement purpose
      description: |
        Purpose of the enhancement - if it solves some problem, precise in particular which. If it benefits the program in some other way, precise in particular why.
        Present the underlying reason why this enhancement makes sense, and what is the context of it.
      placeholder: |
        As of today SteamBadgesDB offers variety of beverages, such as latte macchiato or cappuccino. I'd appreciate if it offered some no-milk options as well, for example espresso or ristretto.
        I believe it'd further improve the program offering the users wider selection, which is very convenient.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What would you like to see as a solution to the purpose specified by you above?
      placeholder: |
        Simply add an option to brew some no-milk types of coffee. The existing logic is fine, we just need wider choice!
    validations:
      required: true
  - type: textarea
    id: why-existing-not-sufficient
    attributes:
      label: Why currently available solutions are not sufficient?
      description: |
        Evaluate the existing solutions in regards to your requirements.
        If something you're suggesting is already possible, then explain to us why the currently available solutions are not sufficient.
        If it's not possible yet, then explain to us why it should be.
      placeholder: |
        I'm allergic to milk, there is currently no option to pick a beverage that doesn't include it.
        Temporarily I'm switching cup mid-brewing as a workaround, but that is suboptimal considering the milk wasted.
    validations:
      required: true
  - type: dropdown
    id: help
    attributes:
      label: Can you help us with this enhancement idea?
      description: |
        SteamBadgeDB is offered for free and our resources are limited.
        Helping us increases the chance of making it happen.
      options:
        - Yes, I can code the solution myself and send a pull request
        - Somehow, I can test and offer feedback, but can't code
        - No, I don't have time, skills or willings for any of that
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Everything else you consider worthy that we didn't ask for.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this form.
