name: SteamBadgesDB-ci

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 19]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Node.js v${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        
    - name: Verify Node.js
      run: node --version
    - name: Verify NPM
      run: npm --version
        
    - name: Build & Test (${{ matrix.configuration }})
      run: npm ci && npm test
