name: SteamBadgesDB-ci

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20, 21]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js v${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        
    - name: Verify Node.js Version
      run: node --version
    - name: Verify npm Version
      run: npm --version
      
    - name: Cache Node.js Modules
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
        enableCrossOsArchive: true
        
    - name: Install npm Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      
    - name: Run Lint (${{ matrix.os }})
      run: npm run lint

    - name: Run Test (${{ matrix.os }})
      run: npm run test
