name: SteamBadgesDB-ci

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 19]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Node.js v${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        
    - name: Verify Node.js & npm Versions
      run: |
        node --version
        npm --version
      
    - name: Cache Node Modules
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
        enableCrossOsArchive: true
        
    - name: Install NPM Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      
    - name: Lint & Testing (${{ matrix.os }})
      run: |
        npm lint
        npm test
