name: SteamBadgesDB-self-update

on:
  schedule:
    # * is a special character in YAML so we have to quote this string
    - cron:  '0 */1 * * *' # every 1 hour

jobs:
    self-update:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Verify Node.js Version
          run: node --version
        - name: Verify npm Version
          run: npm --version

        - name: Cache Node.js Modules
          id: cache
          uses: actions/cache@v3
          with:
            path: node_modules
            key: node-modules-${{ hashFiles('package-lock.json') }}
            enableCrossOsArchive: true

        - name: Install npm Dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: npm ci

        - name: Run SteamCardExchange Scrapper
          run: npm start

        - name: Sync Changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
            commit_message: Automatic badges.json update
            file_pattern: 'data/*.json'
